name: tencent_im_sdk_plugin_example
description: Demonstrates how to use the tencent_im_sdk_plugin plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # tencent_im_sdk_plugin: 
    # When depending on this package from a real application you should use:
    #   tencent_im_sdk_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version. 
    # path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  tencent_im_sdk_plugin: ^1.0.9
  cupertino_icons: ^0.1.3
  toast: ^0.1.5
  dio: ^3.0.9
  json_annotation: ^3.1.0
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+14
  flutter_plugin_record: ^0.3.4
  file_picker: ^2.1.0
  video_player: ^1.0.1
  loading: ^1.0.2
  transparent_image: ^1.0.0
  flutter_video_compress: ^0.3.7+8
  # tencent_tpns_oppo_push_plugin: ^0.0.2
  # tencent_tpns_xiaomi_push_plugin: ^0.0.1
  # tencent_tpns_vivo_push_plugin: ^0.0.1
  device_info: ^1.0.0
  flutter_slidable: ^0.5.7
  # firebase_messaging: ^6.0.16
  flutter_apns: ^1.4.1
  crypto: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  permission_handler: ^4.0.0
  path_provider: ^1.6.22
  json_serializable: ^3.5.0
  build_runner: ^1.10.3
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/person.png
    - images/file.png
    - images/voice_volume_1.png
    - images/voice_volume_2.png
    - images/voice_volume_3.png
    - images/voice_volume_4.png
    - images/voice_volume_5.png
    - images/voice_volume_6.png
    - images/voice_volume_7.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
